// ── Sample library data ───────────────────────────────────────────────────
// Edit this array to customize your library, or use the "+ Add Title" button.

const LIBRARY_DATA = [
  {
    id: 1,
    title: "Inception",
    type: "movie",
    year: 2010,
    genre: "Sci-Fi, Thriller",
    rating: 8.8,
    creator: "Christopher Nolan",
    status: "watched",
    notes: "Mind-bending heist film. The spinning top ending still gets me.",
    poster: ""
  },
  {
    id: 2,
    title: "The Shawshank Redemption",
    type: "movie",
    year: 1994,
    genre: "Drama",
    rating: 9.3,
    creator: "Frank Darabont",
    status: "watched",
    notes: "A timeless story about hope and friendship.",
    poster: ""
  },
  {
    id: 3,
    title: "Interstellar",
    type: "movie",
    year: 2014,
    genre: "Sci-Fi, Adventure",
    rating: 8.6,
    creator: "Christopher Nolan",
    status: "watched",
    notes: "Hans Zimmer's score paired with stunning visuals. A masterpiece.",
    poster: ""
  },
  {
    id: 4,
    title: "Breaking Bad",
    type: "tv",
    year: 2008,
    genre: "Drama, Crime",
    rating: 9.5,
    creator: "Vince Gilligan",
    status: "watched",
    notes: "Best character arc in television history. Walter White's transformation is haunting.",
    poster: ""
  },
  {
    id: 5,
    title: "Succession",
    type: "tv",
    year: 2018,
    genre: "Drama, Comedy",
    rating: 8.8,
    creator: "Jesse Armstrong",
    status: "watched",
    notes: "Sharp writing, incredible performances. 'The Meal' episode is flawless.",
    poster: ""
  },
  {
    id: 6,
    title: "The Bear",
    type: "tv",
    year: 2022,
    genre: "Drama, Comedy",
    rating: 8.7,
    creator: "Christopher Storer",
    status: "watching",
    notes: "Season 2 'Fishes' episode is one of the best hours of TV ever made.",
    poster: ""
  },
  {
    id: 7,
    title: "Dune: Part One",
    type: "movie",
    year: 2021,
    genre: "Sci-Fi, Adventure",
    rating: 8.0,
    creator: "Denis Villeneuve",
    status: "watched",
    notes: "Visually stunning. Denis Villeneuve is the master of sci-fi adaptation.",
    poster: ""
  },
  {
    id: 8,
    title: "Dune: Part Two",
    type: "movie",
    year: 2024,
    genre: "Sci-Fi, Adventure",
    rating: 8.8,
    creator: "Denis Villeneuve",
    status: "watched",
    notes: "Zendaya finally gets screen time. Completely lives up to the hype.",
    poster: ""
  },
  {
    id: 9,
    title: "Severance",
    type: "tv",
    year: 2022,
    genre: "Sci-Fi, Thriller",
    rating: 8.7,
    creator: "Dan Erickson",
    status: "watching",
    notes: "The most original premise in years. Season 2 raised the stakes perfectly.",
    poster: ""
  },
  {
    id: 10,
    title: "The Godfather",
    type: "movie",
    year: 1972,
    genre: "Crime, Drama",
    rating: 9.2,
    creator: "Francis Ford Coppola",
    status: "watched",
    notes: "An offer you can't refuse. Every frame is a painting.",
    poster: ""
  },
  {
    id: 11,
    title: "Parasite",
    type: "movie",
    year: 2019,
    genre: "Thriller, Drama",
    rating: 8.5,
    creator: "Bong Joon-ho",
    status: "watched",
    notes: "Deserved every Oscar. The basement reveal is unforgettable.",
    poster: ""
  },
  {
    id: 12,
    title: "Chernobyl",
    type: "tv",
    year: 2019,
    genre: "Drama, History",
    rating: 9.4,
    creator: "Craig Mazin",
    status: "watched",
    notes: "The most disturbing and important TV I've ever watched.",
    poster: ""
  },
  {
    id: 13,
    title: "2001: A Space Odyssey",
    type: "movie",
    year: 1968,
    genre: "Sci-Fi",
    rating: 8.3,
    creator: "Stanley Kubrick",
    status: "watched",
    notes: "Still baffles and amazes. HAL 9000 remains cinema's greatest villain.",
    poster: ""
  },
  {
    id: 14,
    title: "The Leftovers",
    type: "tv",
    year: 2014,
    genre: "Drama, Mystery",
    rating: 8.3,
    creator: "Damon Lindelof",
    status: "watched",
    notes: "Most emotionally devastating show I've seen. Season 2 is a masterpiece.",
    poster: ""
  },
  {
    id: 15,
    title: "Oppenheimer",
    type: "movie",
    year: 2023,
    genre: "Drama, History",
    rating: 8.9,
    creator: "Christopher Nolan",
    status: "watched",
    notes: "Cillian Murphy is magnetic. The Trinity test sequence is awe-inspiring.",
    poster: ""
  },
  {
    id: 16,
    title: "The Sopranos",
    type: "tv",
    year: 1999,
    genre: "Crime, Drama",
    rating: 9.2,
    creator: "David Chase",
    status: "want",
    notes: "On my list — widely considered the greatest TV show ever made.",
    poster: ""
  },
  {
    id: 17,
    title: "Everything Everywhere All at Once",
    type: "movie",
    year: 2022,
    genre: "Sci-Fi, Comedy, Drama",
    rating: 7.8,
    creator: "Daniels",
    status: "watched",
    notes: "Absurdist chaos that somehow becomes deeply moving. The hot dog hands.",
    poster: ""
  },
  {
    id: 18,
    title: "Shogun",
    type: "tv",
    year: 2024,
    genre: "Drama, History, Action",
    rating: 8.9,
    creator: "Rachel Kondo, Caillin Puttock",
    status: "watched",
    notes: "Swept the Emmys for a reason. Hiroyuki Sanada is incredible.",
    poster: ""
  },
  {
    id: 19,
    title: "The Lion King",
    type: "arwen",
    subtype: "movie",
    year: 1994,
    genre: "Animation, Adventure, Drama",
    rating: 8.5,
    creator: "Roger Allers, Rob Minkoff",
    status: "watched",
    notes: "Hakuna Matata. The circle of life never gets old.",
    poster: ""
  },
  {
    id: 20,
    title: "Finding Nemo",
    type: "arwen",
    subtype: "movie",
    year: 2003,
    genre: "Animation, Adventure, Comedy",
    rating: 8.2,
    creator: "Andrew Stanton",
    status: "watched",
    notes: "Just keep swimming. Pixar at its most charming.",
    poster: ""
  },
  {
    id: 21,
    title: "Toy Story",
    type: "arwen",
    subtype: "movie",
    year: 1995,
    genre: "Animation, Adventure, Comedy",
    rating: 8.3,
    creator: "John Lasseter",
    status: "watched",
    notes: "The one that started it all. Andy's toys hold up perfectly.",
    poster: ""
  },
  {
    id: 22,
    title: "Moana",
    type: "arwen",
    subtype: "movie",
    year: 2016,
    genre: "Animation, Adventure, Comedy",
    rating: 7.6,
    creator: "Ron Clements, John Musker",
    status: "watched",
    notes: "How Far I'll Go is an absolute banger. Tamatoa steals every scene.",
    poster: ""
  },
  {
    id: 23,
    title: "Encanto",
    type: "arwen",
    subtype: "movie",
    year: 2021,
    genre: "Animation, Comedy, Family",
    rating: 7.2,
    creator: "Jared Bush, Byron Howard",
    status: "watched",
    notes: "We don't talk about Bruno. Gorgeous animation and Lin-Manuel Miranda songs.",
    poster: ""
  },
  {
    id: 24,
    title: "Bluey",
    type: "arwen",
    subtype: "tv",
    year: 2018,
    genre: "Animation, Comedy, Family",
    rating: 9.2,
    creator: "Ludo Studio",
    status: "watching",
    notes: "Secretly one of the best shows on TV, full stop. Bandit Heeler is parenting goals.",
    poster: ""
  },
  {
    id: 25,
    title: "Avatar: The Last Airbender",
    type: "arwen",
    subtype: "tv",
    year: 2005,
    genre: "Animation, Action, Adventure",
    rating: 9.3,
    creator: "Michael DiMartino, Bryan Konietzko",
    status: "watched",
    notes: "One of the greatest animated series ever made. Zuko's arc is unmatched.",
    poster: ""
  },
  {
    id: 26,
    title: "Paw Patrol: The Movie",
    type: "arwen",
    subtype: "movie",
    year: 2021,
    genre: "Animation, Adventure, Comedy",
    rating: 5.9,
    creator: "Cal Brunker",
    status: "watched",
    notes: "Arwen loves it. Ryder and the pups save Adventure City.",
    poster: ""
  },
  {
    id: 27,
    title: "Peppa Pig",
    type: "arwen",
    subtype: "tv",
    year: 2004,
    genre: "Animation, Comedy, Family",
    rating: 7.1,
    creator: "Neville Astley, Mark Baker",
    status: "watching",
    notes: "A staple. Every adult secretly knows all the characters.",
    poster: ""
  },
  {
    id: 28,
    title: "Spirited Away",
    type: "arwen",
    subtype: "movie",
    year: 2001,
    genre: "Animation, Adventure, Family",
    rating: 8.6,
    creator: "Hayao Miyazaki",
    status: "want",
    notes: "Studio Ghibli's masterpiece. Perfect for watching together.",
    poster: ""
  }
];
